ex01 : ex01.c
	gcc -o $@.exe $^
ex02 : ex02.c
	gcc -o $@.exe $^
ex03 : ex03.c
	gcc -o $@.exe $^
ex04 : ex04.c
	gcc -o $@.exe $^
ex05 : ex05.c
	gcc -o $@.exe $^
ex06 : ex06.c
	gcc -o $@.exe $^ -lmingw32 -lSDL2main -lSDL2
ex08 : ex08.c
	gcc -o $@.exe $^
q1 : q1.c
	gcc -o $@.exe $^
q6 : q6.c
	gcc -o $@.exe $^
ex09 : ex09.c
	gcc -o $@.exe $^ -lmingw32 -lSDL2main -lSDL2
ex10 : ex10.c ../engine/parser.c ../engine/tile.c
	gcc -o $@.exe $^ -lmingw32 -lSDL2main -lSDL2 -lSDL2_image
mapTool : mapTool.c ../engine/parser.c ../engine/tile.c
	gcc -o $@.exe $^ -lmingw32 -lSDL2main -lSDL2 -lSDL2_image -lSDL2_ttf
