ex01 : ex01.c
	gcc -o $@.exe $^

ex02 : ex02.c
	gcc -o $@.exe $^

ex03 : ex03.c
	gcc -o $@.exe $^

ex04 : ex04.c
	gcc -o $@.exe $^ -lmingw32 -lSDL2main -lSDL2

ex05 : ex05.c
	gcc -o $@.exe $^ -lmingw32 -lSDL2main -lSDL2

ex06 : ex06.c
	gcc -o $@.exe $^

ex07 : ex07.c
	gcc -o $@.exe $^ -lmingw32 -lSDL2main -lSDL2
	
ex08 : ex08.c
	gcc -o $@.exe $^

ex09 : ex09.c
	gcc -o $@.exe $^

ex10 : ex10.c
	gcc -o $@.exe $^

ex11 : ex11.c
	gcc -o $@.exe $^

q4 : q4.c
	gcc -o $@.exe $^ -lmingw32 -lSDL2main -lSDL2

q6 : q6.c
	gcc -o $@.exe $^

q6-2 : q6-2.c
	gcc -o $@.exe $^
	