ex01 : ex01.c ../engine/graph.c
	gcc -g -o $@ $^ -lmingw32 -lSDL2main -lSDL2 -lSDL2_image -lSDL2_ttf
mapTool-2 : mapTool-2.c ../engine/parser.c ../engine/tile.c ../engine/ui/button.c
	gcc -o $@.exe $^ -lmingw32 -lSDL2main -lSDL2 -lSDL2_image -lSDL2_ttf
ex02 : ex02.c ../engine/graph.c ../engine/core.c ../engine/entity/sprite.c
	gcc -g -o $@ $^ -lmingw32 -lSDL2main -lSDL2 -lSDL2_image -lSDL2_ttf